-- local lib = require("neotest.lib")
-- local position = require("neotest-scala.position")
-- local types = require("neotest-scala.types")
--
-- local M = {}
--
-- M.type = types.TEST_FRAMEWORKS.MUNIT
--
-- ---@param path string
-- ---@return string[]
-- function M.get_test_suites_in_file(path)
--     local file_content = lib.files.read(path)
--     local ts = vim.treesitter
--     local parser = ts.get_string_parser(file_content, "scala")
--     local tree = parser:parse()[1]
--     local root = tree:root()
--
--     local query = [[
--         (class_definition
--             name: (identifier) @namespace.name
--             extend: (extends_clause
--             type: (stable_type_identifier))) @namespace.definition
--     ]]
--
--     local query_obj = ts.query.parse("scala", query)
--
--     local test_suites = {}
--
--     for _, captures, _ in query_obj:iter_matches(root, file_content) do
--         for id, node in pairs(captures) do
--             local name = query_obj.captures[id] -- capture name
--
--             if name == "namespace.name" then
--                 local test_suite_name = vim.treesitter.get_node_text(node, file_content)
--
--                 table.insert(test_suites, test_suite_name)
--             end
--         end
--     end
--
--     return test_suites
-- end
--
-- -- FIXME: this is duplicated; move this to position.lua
-- ---@param path string
-- ---@return string|nil
-- function M.get_package_name(path)
--     local file_content = lib.files.read(path)
--     local ts = vim.treesitter
--     local parser = ts.get_string_parser(file_content, "scala")
--     local tree = parser:parse()[1]
--     local root = tree:root()
--
--     local query = [[
--       (package_clause (package_identifier) @package)
--     ]]
--
--     local query_obj = ts.query.parse("scala", query)
--
--     for _, captures, _ in query_obj:iter_matches(root, file_content) do
--         for id, node in pairs(captures) do
--             local name = query_obj.captures[id] -- capture name
--             if name == "package" then
--                 local package_name = vim.treesitter.get_node_text(node, file_content)
--
--                 return package_name
--             end
--         end
--     end
--
--     return nil -- If no package found
-- end
--
-- ---@param position neotest.Position
-- ---@return string
-- function M.get_position_name(position)
--     -- when the position is parsed, its name is wrapped in quotes for some reason
--     -- so, we'll strip them out so we can use the name as an id
--     local position_name, _ = string.gsub(position.name, [[^"(.+)"$]], "%1")
--     -- local escaped_test_name = position_name:gsub("([%^%$%(%)%%%.%[%]%*%+%-%?])", "%%%1")
--
--     return position_name
-- end
--
-- ---@param position neotest.Position
-- ---@param parents neotest.Position[]
-- ---@return string
-- function M.build_position_id(position, parents)
--     local type = position.type
--
--     local position_name = M.get_position_name(position)
--
--     if type == "namespace" then
--         -- if we're given a namespace, and it has no parents
--         -- then we want to prefix the id with the package name
--         if #parents == 0 then
--             -- local containing_object_name = M.get_container_object(position.path, position.range).name
--             local package_name = M.get_package_name(position.path)
--             return package_name .. "." .. position_name
--         else
--             -- otherwise, if it has parents, we'll return just the name
--             -- TODO: fix this properly so that we supported unlimited nesting
--             -- get the first parent
--             local parent = parents[1]
--             return parent.id .. "." .. position_name
--         end
--     elseif type == "test" then
--         -- FIXME: clean this up, right?
--         local parent_values = {}
--
--         for i, parent in ipairs(parents) do
--             if i == 1 then
--                 table.insert(parent_values, parent.id)
--             else
--                 local parent_name = M.get_position_name(parent)
--
--                 table.insert(parent_values, parent_name)
--             end
--         end
--
--         local value = table.concat(
--             vim.iter({
--                 parent_values,
--             })
--                 :flatten()
--                 :totable(),
--             "."
--         )
--
--         -- FIXME: this is a poor name for this variable
--         local updated_value = value .. "." .. position_name
--
--         return updated_value
--     else
--         -- FIXME: what do we want to do here?
--         -- basically, we have an unknown Node Type here
--         return ""
--     end
-- end
--
-- function M.parse_tree(tree)
--     local type = tree:data().type
--
--     if type == "file" then
--         local package_name = M.get_package_name(tree:data().path)
--         local test_suites = M.get_test_suites_in_file(tree:data().path)
--
--         local only = {}
--
--         for _, test_suite in ipairs(test_suites) do
--             table.insert(only, package_name .. "." .. test_suite)
--         end
--
--         return {
--             type = type,
--             only = only,
--             positions = {},
--         }
--     end
--
--     if type == "namespace" then
--         return {
--             type = type,
--             only = {
--                 tree:data().id,
--             },
--             positions = {},
--         }
--     end
--
--     if type == "test" then
--         local package_name = M.get_package_name(tree:data().path)
--         -- FIXME: this only supports one test suite per file
--         -- we'll need to support more than one test suite per file
--         -- and we'll need to find the parent test suite for the current test location
--         local test_suites = M.get_test_suites_in_file(tree:data().path)
--
--         local test_suite = test_suites[1]
--
--         return {
--             type = type,
--             only = {
--                 package_name .. "." .. test_suite,
--             },
--             positions = {
--                 {
--                     id = tree:data().id,
--                     name = M.get_position_name(tree:data()),
--                 },
--             },
--         }
--     end
--
--     if type == "dir" then
--         local only = {}
--
--         for _, child in tree:iter_nodes() do
--             if child:data().type == "namespace" then
--                 table.insert(only, child:data().id)
--             end
--         end
--
--         return {
--             type = type,
--             only = only,
--             positions = {},
--         }
--     end
--
--     return nil
-- end
--
-- ---@param path string
-- ---@return neotest.Position[]
-- function M.discover_positions(path)
--     print("#discover_positions")
--     local query = [[
--         (class_definition
--             name: (identifier) @namespace.name
--             extend: (extends_clause
--             type: (stable_type_identifier))) @namespace.definition
--
--         ((call_expression
--             function: (call_expression
--             function: (identifier) @func_name (#match? @func_name "test")
--             arguments: (arguments (string) @test.name))
--         )) @test.definition
--
--         ((call_expression
--             function: (call_expression
--             function: (identifier) @func_name (#match? @func_name "suite")
--             arguments: (arguments (string) @namespace.name))
--         )) @namespace.definition
--     ]]
--
--     local positions = lib.treesitter.parse_positions(path, query, {
--         nested_tests = true,
--         require_namespaces = true,
--         position_id = M.build_position_id,
--     })
--
--     return positions
-- end
--
-- function M.extract_test_suites(tree)
--     local type = tree:data().type
--
--     print("#extract_test_suites")
--     print("type: " .. type)
--
--     if type == "test" then
--         local test_name = string.gsub(tree:data().name, '"', "")
--         local parent_tree = tree:parent()
--         local parent_name = parent_tree:data().name
--
--         local test_id = tree:data().id
--         -- Escape special characters in test_name to safely use it in the pattern
--         local escaped_test_name = test_name:gsub("([%^%$%(%)%%%.%[%]%*%+%-%?])", "%%%1")
--
--         -- Use gsub to remove test_name from test_id
--         -- remove the test_name from the end of test_id
--         local result = test_id:sub(1, -string.len(test_name) - 1)
--
--         local result_without_trailing_period = result:sub(1, -2)
--
--         return {
--             type = type,
--             test_name = test_name,
--             test_suites = { result_without_trailing_period },
--         }
--     end
--
--     -- FIXME: obviously this is duplicated with the below type == "namespace" case
--     if type == "file" then
--         local test_suites = {}
--
--         for _, child in tree:iter_nodes() do
--             if child:data().type == "namespace" then
--                 print(child:data().id)
--                 table.insert(test_suites, child:data().id)
--             end
--         end
--
--         return {
--             type = type,
--             test_suites = test_suites,
--         }
--     end
--
--     -- FIXME: obviously this is duplicated with the above type == "file" case
--     if type == "namespace" then
--         local test_suites = {}
--
--         -- print("-----------------------")
--         -- print("it's a namespace, and I'm extracting the test suites ...")
--
--         for _, child in tree:iter_nodes() do
--             if child:data().type == "namespace" then
--                 print(child:data().id)
--                 table.insert(test_suites, child:data().id)
--             end
--         end
--
--         return {
--             type = type,
--             test_suites = test_suites,
--         }
--     end
--
--     if type == "dir" then
--         local packages = {}
--
--         for _, child in tree:iter_nodes() do
--             if child:data().type == "namespace" then
--                 local package = position.get_package_name(child:data().path)
--
--                 table.insert(packages, package .. "." .. child:data().name)
--             end
--         end
--
--         return {
--             type = type,
--             test_suites = packages,
--         }
--     end
-- end
--
-- return M
