-- require("setup_test_environment")
--
-- local files = require("neotest.lib").files
-- local async = require("nio").tests
-- local position = require("neotest-scala.position")
--
-- local framework_adapter = require("neotest-scala.test_parsers.munit_test_parser")
--
-- -- TODO: obviously this isn't a "single" spec anymore
-- local munit_spec = [[
--   package foo.bar
--
--   import foo.Hello
--
--   class FooSuite extends munit.FunSuite:
--     test("Foo.Bar"):
--       assertEquals(Hello.msg, "Hello World!")
--
--     test("Foo Bar"):
--       assertEquals(Hello.msg, "Hello World.")
--
--     test("Bar Foo"):
--       assertEquals(Hello.msg, "Hello World!")
--
--     test("Foo Baz"):
--       assertEquals(Hello.msg, "Hello World!")
-- ]]
--
-- -- TODO: move this to a common helper package
-- local function assert_has_position(tree, pos_id)
--     local position_ids = {}
--
--     for _, node in tree:iter_nodes() do
--         local data = node:data()
--
--         table.insert(position_ids, data.id)
--     end
--
--     assert(
--         position.has_position(tree, pos_id),
--         "Position " .. pos_id .. " not found in positions: " .. vim.inspect(position_ids)
--     )
-- end
--
-- -- TODO: move this to a common helper package
-- local function assert_has_positions(spec, pos_ids)
--     local fpath = vim.fn.tempname() .. ".scala"
--     files.write(fpath, spec)
--
--     local tree = framework_adapter.discover_positions(fpath)
--
--     for _, pos_id in ipairs(pos_ids) do
--         assert_has_position(tree, pos_id)
--     end
-- end
--
-- describe("MUnit Test Framework", function()
--     describe("find_positions", function()
--         async.it("should find the Test Suite + Test in a file", function()
--             local expected = {
--                 "foo.bar.FooSuite", -- this is the Suite
--                 "foo.bar.FooSuite.Foo.Bar", -- this is a test
--                 "foo.bar.FooSuite.Foo Bar", -- this is a test
--                 "foo.bar.FooSuite.Bar Foo", -- this is a test
--                 "foo.bar.FooSuite.Foo Baz", -- this is a test
--             }
--
--             assert_has_positions(munit_spec, expected)
--         end)
--     end)
--
--     describe("parse_tree", function()
--         async.it("should be able to parse a File and find the FunSuites", function()
--             local fpath = vim.fn.tempname() .. ".scala"
--             files.write(fpath, munit_spec)
--
--             local tree = framework_adapter.discover_positions(fpath)
--             local test_position = position.get_position_by_name(tree, "0.scala")
--
--             local result = framework_adapter.parse_tree(test_position)
--
--             local expected = {
--                 type = "file",
--                 only = {
--                     "foo.bar.FooSuite",
--                 },
--                 positions = {},
--             }
--
--             assert.is_same(expected, result)
--         end)
--
--         async.it("should be able to parse a Namespace and return the Test Suite", function()
--             local fpath = vim.fn.tempname() .. ".scala"
--             files.write(fpath, munit_spec)
--
--             local positions = framework_adapter.discover_positions(fpath)
--             local test_position = position.find_position(positions, "foo.bar.FooSuite")
--
--             local result = framework_adapter.parse_tree(test_position)
--
--             local expected = {
--                 type = "namespace",
--                 only = {
--                     "foo.bar.FooSuite",
--                 },
--                 positions = {},
--             }
--
--             assert.is_same(expected, result)
--         end)
--
--         async.it("should be able to parse a Test", function()
--             local fpath = vim.fn.tempname() .. ".scala"
--             files.write(fpath, munit_spec)
--
--             local positions = framework_adapter.discover_positions(fpath)
--             local test_position = position.find_position(positions, "foo.bar.FooSuite.Bar Foo")
--
--             local result = framework_adapter.parse_tree(test_position)
--
--             local expected = {
--                 type = "test",
--                 only = {
--                     "foo.bar.FooSuite",
--                 },
--                 positions = {
--                     {
--                         id = "foo.bar.FooSuite.Bar Foo",
--                         name = "Bar Foo",
--                     },
--                 },
--             }
--
--             assert.is_same(expected, result)
--         end)
--     end)
-- end)
